In [1]:
import numpy as np
import pandas as pd
import re

In [2]:
with open('exxon_wiki_text.txt','r') as f:
    txt=f.read()

In [3]:
txt

'Exxon Mobil Corporation\nFloating cube at ExxonMobil headquarters near Spring, Texas\nFormerly Standard Oil Company (New Jersey) (1882[1]-1973)\nExxon Corporation (1973-1999)\n\nFounded\tAugust 5, 1882; 141 years ago (as Standard Oil of New Jersey)[1]\nFounder\tSplit from Standard Oil by the US Supreme Court in 1911; merged with Mobil in 1999 to form present name\nHeadquarters\tUnincorporated Harris County near Spring, Texas, U.S.\nArea served\tWorldwide\nKey people (Chairman & CEO)\tDarren Woods\n\nProducts Crude oil, Oil products, Natural gas, Petrochemicals, Power generation\nRevenue\tDecrease US$344.6 billion (2023)[3]\nOperating income\tDecrease US$52.78 billion (2023)[3]\nNet income\tDecrease US$36.01 billion (2023)[3]\nTotal assets\tIncrease US$376.3 billion (2023)[3]\nTotal equity\tIncrease US$204.8 billion (2023)[3]\nNumber of employees\t61,500 (2023)[3]\nParent\tStandard Oil (1882-1911)\nSubsidiaries Exxon Neftegas ExxonMobil Australia ExxonMobil Nigeria Imperial Oil SeaRive

In [4]:
pattern=re.compile(r'\[\d*\]')

In [5]:
txt=pattern.sub(r'',txt)

In [6]:
txt=re.sub(r'\n+','\n',txt)

In [7]:
import nltk

In [8]:
print(txt)

Exxon Mobil Corporation
Floating cube at ExxonMobil headquarters near Spring, Texas
Formerly Standard Oil Company (New Jersey) (1882-1973)
Exxon Corporation (1973-1999)
Founded	August 5, 1882; 141 years ago (as Standard Oil of New Jersey)
Founder	Split from Standard Oil by the US Supreme Court in 1911; merged with Mobil in 1999 to form present name
Headquarters	Unincorporated Harris County near Spring, Texas, U.S.
Area served	Worldwide
Key people (Chairman & CEO)	Darren Woods
Products Crude oil, Oil products, Natural gas, Petrochemicals, Power generation
Revenue	Decrease US$344.6 billion (2023)
Operating income	Decrease US$52.78 billion (2023)
Net income	Decrease US$36.01 billion (2023)
Total assets	Increase US$376.3 billion (2023)
Total equity	Increase US$204.8 billion (2023)
Number of employees	61,500 (2023)
Parent	Standard Oil (1882-1911)
Subsidiaries Exxon Neftegas ExxonMobil Australia ExxonMobil Nigeria Imperial Oil SeaRiver Maritime XTO Energy.
Website	corporate.exxonmobil.com
Ex

In [9]:
from nltk import sent_tokenize

In [10]:
import tensorflow as tf

In [11]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [12]:
tokeniser=Tokenizer()

In [13]:
tokeniser.fit_on_texts([txt])

In [15]:
tokeniser.word_index

{'the': 1,
 'and': 2,
 'of': 3,
 'in': 4,
 'exxonmobil': 5,
 'oil': 6,
 'to': 7,
 'a': 8,
 'company': 9,
 'its': 10,
 'is': 11,
 'as': 12,
 'with': 13,
 'million': 14,
 'acres': 15,
 '1': 16,
 'by': 17,
 'it': 18,
 '000': 19,
 'exxon': 20,
 'largest': 21,
 'km2': 22,
 'standard': 23,
 'which': 24,
 'carbon': 25,
 'mobil': 26,
 'united': 27,
 'new': 28,
 'states': 29,
 'has': 30,
 'for': 31,
 'gas': 32,
 'billion': 33,
 'that': 34,
 'was': 35,
 "exxonmobil's": 36,
 'ceo': 37,
 '6': 38,
 'energy': 39,
 'companies': 40,
 'are': 41,
 'also': 42,
 'on': 43,
 '4': 44,
 'jersey': 45,
 '2023': 46,
 'were': 47,
 'into': 48,
 'low': 49,
 '2022': 50,
 'president': 51,
 'us': 52,
 'world': 53,
 "company's": 54,
 '0': 55,
 'former': 56,
 'at': 57,
 'texas': 58,
 'from': 59,
 '3': 60,
 'plastic': 61,
 'other': 62,
 'one': 63,
 'global': 64,
 'spill': 65,
 'offshore': 66,
 '5': 67,
 'name': 68,
 '500': 69,
 'had': 70,
 'most': 71,
 'than': 72,
 'barrels': 73,
 'spills': 74,
 '2': 75,
 'operations': 7

In [16]:
sent=sent_tokenize(txt)

In [24]:
len(sent)

135

In [27]:
for i in sent:
    print(i,'\n')

Exxon Mobil Corporation
Floating cube at ExxonMobil headquarters near Spring, Texas
Formerly Standard Oil Company (New Jersey) (1882-1973)
Exxon Corporation (1973-1999)
Founded	August 5, 1882; 141 years ago (as Standard Oil of New Jersey)
Founder	Split from Standard Oil by the US Supreme Court in 1911; merged with Mobil in 1999 to form present name
Headquarters	Unincorporated Harris County near Spring, Texas, U.S.
Area served	Worldwide
Key people (Chairman & CEO)	Darren Woods
Products Crude oil, Oil products, Natural gas, Petrochemicals, Power generation
Revenue	Decrease US$344.6 billion (2023)
Operating income	Decrease US$52.78 billion (2023)
Net income	Decrease US$36.01 billion (2023)
Total assets	Increase US$376.3 billion (2023)
Total equity	Increase US$204.8 billion (2023)
Number of employees	61,500 (2023)
Parent	Standard Oil (1882-1911)
Subsidiaries Exxon Neftegas ExxonMobil Australia ExxonMobil Nigeria Imperial Oil SeaRiver Maritime XTO Energy. 

Website	corporate.exxonmobil.com


In [35]:
for sentence in sent:
    print(tokeniser.texts_to_sequences([sentence])[0])

[20, 26, 80, 499, 500, 57, 5, 146, 195, 147, 58, 501, 23, 6, 9, 28, 45, 196, 284, 20, 80, 284, 81, 285, 286, 67, 196, 502, 287, 503, 12, 23, 6, 3, 28, 45, 288, 504, 59, 23, 6, 17, 1, 52, 505, 506, 4, 148, 101, 13, 26, 4, 81, 7, 289, 290, 68, 146, 507, 291, 292, 195, 147, 58, 82, 83, 197, 508, 149, 150, 509, 84, 37, 151, 85, 116, 293, 6, 6, 116, 152, 32, 510, 294, 295, 102, 198, 52, 511, 38, 33, 46, 153, 296, 198, 52, 512, 513, 33, 46, 514, 296, 198, 52, 515, 516, 33, 46, 297, 517, 298, 52, 518, 60, 33, 46, 297, 519, 298, 52, 520, 117, 33, 46, 299, 3, 300, 301, 69, 46, 521, 23, 6, 196, 148, 302, 20, 303, 5, 304, 5, 305, 199, 6, 306, 307, 200, 39]
[201, 103, 5, 522, 5, 80, 523, 308, 7, 20, 11, 86, 104, 524, 6, 2, 32, 80, 2, 1, 21, 525, 309, 3, 526, 527, 528, 23, 6]
[1, 9, 24, 529, 10, 290, 68, 4, 81, 87, 1, 88, 3, 20, 2, 26, 11, 310, 202, 118, 1, 530, 6, 2, 32, 105, 2, 203, 18, 11, 42, 8, 311, 119, 24, 204, 61, 205, 312, 2, 62, 106, 116]
[5, 11, 313, 195, 1, 154, 314, 3, 147, 58, 155, 20

In [34]:
[tokeniser.index_word[x] for x in [20, 26, 80, 499, 500, 57, 5, 146, 195, 147, 58, 501, 23, 6] ]

['exxon',
 'mobil',
 'corporation',
 'floating',
 'cube',
 'at',
 'exxonmobil',
 'headquarters',
 'near',
 'spring',
 'texas',
 'formerly',
 'standard',
 'oil']

In [41]:
input_sequence=[]
for sentence in sent:
    tokenised_sentence=tokeniser.texts_to_sequences([sentence])[0]
    for i in range(1,len(tokenised_sentence)):
        input_sequence.append(tokenised_sentence[:i+1])

input_sequence

[[20, 26],
 [20, 26, 80],
 [20, 26, 80, 499],
 [20, 26, 80, 499, 500],
 [20, 26, 80, 499, 500, 57],
 [20, 26, 80, 499, 500, 57, 5],
 [20, 26, 80, 499, 500, 57, 5, 146],
 [20, 26, 80, 499, 500, 57, 5, 146, 195],
 [20, 26, 80, 499, 500, 57, 5, 146, 195, 147],
 [20, 26, 80, 499, 500, 57, 5, 146, 195, 147, 58],
 [20, 26, 80, 499, 500, 57, 5, 146, 195, 147, 58, 501],
 [20, 26, 80, 499, 500, 57, 5, 146, 195, 147, 58, 501, 23],
 [20, 26, 80, 499, 500, 57, 5, 146, 195, 147, 58, 501, 23, 6],
 [20, 26, 80, 499, 500, 57, 5, 146, 195, 147, 58, 501, 23, 6, 9],
 [20, 26, 80, 499, 500, 57, 5, 146, 195, 147, 58, 501, 23, 6, 9, 28],
 [20, 26, 80, 499, 500, 57, 5, 146, 195, 147, 58, 501, 23, 6, 9, 28, 45],
 [20, 26, 80, 499, 500, 57, 5, 146, 195, 147, 58, 501, 23, 6, 9, 28, 45, 196],
 [20,
  26,
  80,
  499,
  500,
  57,
  5,
  146,
  195,
  147,
  58,
  501,
  23,
  6,
  9,
  28,
  45,
  196,
  284],
 [20,
  26,
  80,
  499,
  500,
  57,
  5,
  146,
  195,
  147,
  58,
  501,
  23,
  6,
  9,
  28,
  45

In [42]:
" ".join([tokeniser.index_word[x] for x in [5,
  30,
  90,
  225,
  343,
  588,
  31,
  166,
  344,
  2,
  10,
  120,
  3,
  94,
  109,
  226,
  128,
  1,
  589,
  590,
  34,
  129]])

'exxonmobil has been widely criticized mostly for environmental incidents and its history of climate change denial against the scientific consensus that fossil'

In [43]:
len(input_sequence)

3927

In [51]:
max([len(x) for x in input_sequence])

148

In [52]:
from keras.preprocessing.sequence import pad_sequences

In [55]:
padded_input_sequences=pad_sequences(input_sequence)

In [59]:
len(padded_input_sequences[1])

148

In [60]:
padded_input_sequences

array([[   0,    0,    0, ...,    0,   20,   26],
       [   0,    0,    0, ...,   20,   26,   80],
       [   0,    0,    0, ...,   26,   80,  499],
       ...,
       [   0,    0,    0, ..., 1283,  115,  282],
       [   0,    0,    0, ...,  115,  282,   93],
       [   0,    0,    0, ...,  282,   93,  498]])

In [62]:
X=padded_input_sequences[:,:-1]

In [63]:
X

array([[   0,    0,    0, ...,    0,    0,   20],
       [   0,    0,    0, ...,    0,   20,   26],
       [   0,    0,    0, ...,   20,   26,   80],
       ...,
       [   0,    0,    0, ...,    1, 1283,  115],
       [   0,    0,    0, ..., 1283,  115,  282],
       [   0,    0,    0, ...,  115,  282,   93]])

In [64]:
padded_input_sequences[:,-1]

array([ 26,  80, 499, ..., 282,  93, 498])

In [65]:
y=padded_input_sequences[:,-1]

In [66]:
X.shape,y.shape

((3927, 147), (3927,))

In [70]:
token_count=len(tokeniser.word_index)
token_count

1283

In [71]:
from keras.utils import to_categorical

In [73]:
y=to_categorical(y,num_classes=token_count+1)

In [79]:
y.shape

(3927, 1284)

In [80]:
from keras.models import Sequential

In [88]:
from keras.layers import Embedding,Dense,LSTM

In [92]:
model=Sequential()
model.add(Embedding(y.shape[1],100))
model.add(LSTM(150))
model.add(Dense(y.shape[1],activation='softmax'))

In [94]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [95]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_1 (LSTM)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [96]:
model.fit(X,y,epochs=50)

Epoch 1/100
123/123 ━━━━━━━━━━━━━━━━━━━━ 19s 128ms/step - accuracy: 0.0438 - loss: 6.7732
Epoch 2/100
123/123 ━━━━━━━━━━━━━━━━━━━━ 18s 149ms/step - accuracy: 0.0509 - loss: 6.1856
Epoch 3/100
123/123 ━━━━━━━━━━━━━━━━━━━━ 14s 116ms/step - accuracy: 0.0549 - loss: 6.0121
Epoch 4/100
123/123 ━━━━━━━━━━━━━━━━━━━━ 11s 92ms/step - accuracy: 0.0747 - loss: 5.8073
Epoch 5/100
123/123 ━━━━━━━━━━━━━━━━━━━━ 10s 81ms/step - accuracy: 0.0887 - loss: 5.5945
Epoch 6/100
123/123 ━━━━━━━━━━━━━━━━━━━━ 10s 78ms/step - accuracy: 0.1158 - loss: 5.2714
Epoch 7/100
123/123 ━━━━━━━━━━━━━━━━━━━━ 13s 102ms/step - accuracy: 0.1312 - loss: 4.9820
Epoch 8/100
123/123 ━━━━━━━━━━━━━━━━━━━━ 16s 133ms/step - accuracy: 0.1547 - loss: 4.7190
Epoch 9/100
123/123 ━━━━━━━━━━━━━━━━━━━━ 15s 125ms/step - accuracy: 0.1950 - loss: 4.3506
Epoch 10/100
123/123 ━━━━━━━━━━━━━━━━━━━━ 10s 77ms/step - accuracy: 0.2024 - loss: 4.1506
Epoch 11/100
123/123 ━━━━━━━━━━━━━━━━━━━━ 10s 79ms/step - accuracy: 0.2375 - loss: 3.8861
Epoch 12/100


In [97]:
import pickle

In [98]:
with open('model_1.pkl','wb')as f:
    pickle.dump(model,f)

AttributeError: Can't pickle local object 'Layer._initializer_tracker.<locals>.<lambda>'

In [107]:
text='oil'
#tokenize
token_text=tokeniser.texts_to_sequences([text])[0]
#padding
padded_token_text=pad_sequences([token_text],maxlen=X.shape[1],padding='pre')
#prediction
prediction=model.predict(padded_token_text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step


In [108]:
prediction

array([[1.3018794e-09, 4.3632042e-10, 1.1200530e-03, ..., 5.2370264e-09,
        2.5254345e-11, 1.0596027e-08]], dtype=float32)

In [110]:
len(prediction[0])

1284

In [111]:
np.argmax(prediction[0])

74

In [112]:
tokeniser.index_word[np.argmax(prediction[0])]

'spills'

In [127]:
def predict_text(text):
    for i in range(20):
        text=text
        token_text=tokeniser.texts_to_sequences([text])[0]
        padded_token_text=pad_sequences([token_text],maxlen=X.shape[1],padding='pre')
        prediction=model.predict(padded_token_text,verbose=0)
        text=text+' '+tokeniser.index_word[np.argmax(prediction[0])]
        print(text)

In [135]:
predict_text('Exxonmobil traces')

Exxonmobil traces its
Exxonmobil traces its present
Exxonmobil traces its present name
Exxonmobil traces its present name in
Exxonmobil traces its present name in 1999
Exxonmobil traces its present name in 1999 per
Exxonmobil traces its present name in 1999 per the
Exxonmobil traces its present name in 1999 per the merger
Exxonmobil traces its present name in 1999 per the merger of
Exxonmobil traces its present name in 1999 per the merger of exxon
Exxonmobil traces its present name in 1999 per the merger of exxon and
Exxonmobil traces its present name in 1999 per the merger of exxon and mobil
Exxonmobil traces its present name in 1999 per the merger of exxon and mobil is
Exxonmobil traces its present name in 1999 per the merger of exxon and mobil is vertically
Exxonmobil traces its present name in 1999 per the merger of exxon and mobil is vertically integrated
Exxonmobil traces its present name in 1999 per the merger of exxon and mobil is vertically integrated across
Exxonmobil traces 